spring:
  profiles:
    active: dev
  thymeleaf:
    enabled: true
    #默认是classpath:/templates/
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
#mybatis配置    
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
#日志文件配置
logging:
  config: classpath:logback-spring.xml
  
#七牛云图床配置
qiniucloud:
  accessKey: vRxHtqsnLfzK2h2DTGcEfFlLLDDNgqAvoZf0H08D
  secretKey: 5No0lIzPOv2pYDX9wPkFFh_kE99lvpPia0nA0ZPH
  domain: scss.easyblog.top
  bucket-name: scs-pro